name: animese
description: Aplicativo de anime
version: 2.0.3+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.7  #dados no celular
  http: ^0.12.0+4 #Rquisição
  video_box: ^0.11.4
  cached_network_image: ^2.1.0+1
  firebase_admob: ^0.9.3+2




dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/logo/NameRe.png
    - assets/logo/Name.png
    - assets/logo/NameIcon.png
    - assets/logo/Icon.png
    - assets/imgs/loading.gif


  uses-material-design: true

